### ISSUE TITLE
User Agreement popup on front screen

### ISSUE THREAD

**Issue by MarkvdVorst** [wearefrank/xslt-debugger-webapp#14]
![image](https://github.com/wearefrank/xslt-debugger-webapp/assets/34445874/dffafc80-6d99-4e95-ab1e-8fefaf163d20)

User needs to accept terms before being able to use the program

**Comment by Matthbo** [comment]
What terms or conditions would the user need to accept here?
We dont collect or track user data, we dont have a system where only licensed user can interact with the software and it can't be for cookies because that would need a different GDPR compliant popup window.
We also shouldnt be using cookies eitherway, but thats maybe a concern for later.

So what is the purpose of this other than to mirror what the competition does?

**Comment by MarkvdVorst** [comment]
sorry. should have clarified. The xslt created by the user is shared with everybody. the purpose of this popup is so that the user cannot dismiss the disclaimer that is currently at the bottom and has to accept the condition that their xslt data will be open to the public before using it. 
this popup would therefore replace the disclaimer footer on the current webapp.
